#!/bin/sh
set -e

# compile
qmake QDJANGO_PROFILE=true
make

# run tests
QDJANGO_DB_DRIVER=QSQLITE QDJANGO_DB_NAME=/tmp/qdjango_test.db tests/run.py
QDJANGO_DB_DRIVER=QMYSQL QDJANGO_DB_NAME=qdjango_test QDJANGO_DB_USER=travis tests/run.py
QDJANGO_DB_DRIVER=QPSQL QDJANGO_DB_NAME=qdjango_test QDJANGO_DB_USER=postgres tests/run.py
exit 0

# generate coverage report
TRACEFILE=coverage.info
rm -f $TRACEFILE
lcov --capture --directory src -o $TRACEFILE --no-external
lcov --remove $TRACEFILE \*moc_\* -o $TRACEFILE.clean
mv $TRACEFILE.clean $TRACEFILE

rm -rf coverage
genhtml -o coverage $TRACEFILE
echo "ok"
