#!/bin/sh
set -e

sudo apt-get update -qq

if [ "$QT_SELECT" = "qt4" ]; then
    sudo apt-get install -qq libqt4-dev libqt4-sql-mysql libqt4-sql-odbc libqt4-sql-psql libqt4-sql-sqlite
else
    sudo apt-get install -qq qtbase5-dev libqt5sql5-mysql libqt5sql5-odbc libqt5sql5-psql libqt5sql5-sqlite
fi

sudo apt-get install -qq lcov odbcinst libmyodbc odbc-postgresql
sudo apt-get install -qq mysql-server postgresql
