#!/bin/sh
set -e

if [ "$QT_SELECT" = "qt4" ]; then
    sudo apt-get update
    sudo apt-get install libqt4-dev libqt4-sql-mysql libqt4-sql-odbc libqt4-sql-psql libqt4-sql-sqlite
else
    sudo add-apt-repository -y ppa:ubuntu-sdk-team/ppa
    sudo apt-get update
    sudo apt-get install qtbase5-dev libqt5sql5-mysql libqt5sql5-odbc libqt5sql5-psql libqt5sql5-sqlite
fi
sudo apt-get install lcov odbcinst libmyodbc odbc-postgresql
